### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by kazihussain11** [bryanbcook/azdevops-testplan-extension#18]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/endotronix

The Technology stack that best describes my scenario:

- [x] Other: Cypress

Result format that I plan to use:

- [x] JUnit

**Comment by bryanbcook** [comment]
@kazihussain11 - you're also set. you'll find the extension in your organization under _Organization Settings > General : Extensions_ and then _Shared_ tab.
