### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by pawanjenu** [bryanbcook/azdevops-testplan-extension#22]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/SorocoProducts`):

- Organization Name: https://dev.azure.com/SorocoProducts

The Technology stack that best describes my scenario:

- [x] Other: python

Result format that I plan to use:

- [x] JUnit

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing
