### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by farfush** [bryanbcook/azdevops-testplan-extension#23]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/wonderknd

The Technology stack that best describes my scenario:

- [x] .NET
- [x] JavaScript / TypeScript

Result format that I plan to use:

- [x] JUnit
- [x] xUnit

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing
