### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by QaTest2024** [bryanbcook/azdevops-testplan-extension#26]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/suezsmartsolutions

The Technology stack that best describes my scenario:

- [ ] Java
- [ ] JavaScript / TypeScript
- [ ] Other: cypress

Result format that I plan to use:

- [ ] JUnit
- [ ] xUnit
- [ ] cucumber

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing
