### ISSUE TITLE
I want to try the extension, thank you

### ISSUE THREAD

**Issue by yehaibo** [bryanbcook/azdevops-testplan-extension#29]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/slb1-swt

The Technology stack that best describes my scenario:

- [x] .NET

Result format that I plan to use:

- [x] MSTest (trx)

**Comment by bryanbcook** [comment]
Sorry for the delay.

Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing

**Comment by bryanbcook** [comment]
@yehaibo i discovered a bug in the task.json definition that did not accept mstest as an option for the testformat. this has been addressed in the latest version. please advise if you see any issues.
