### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by LeaCCC** [bryanbcook/azdevops-testplan-extension#38]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- [ ] (required) Organization Name: https://dev.azure.com/_______

The Technology stack that best describes my scenario:

- [x] .NET

Result format that I plan to use:

- [x] JUnit
- [x] MSTest (trx)

The Azure Pipeline Agent I intended to use is a:

- [x] Windows - Self-hosted

I intend to use the Test Plan extension in:

- [x] YAML Pipeline
- [x] Designer-based (Classic) Build Pipeline

**Comment by bryanbcook** [comment]
@LeaCCC I need your organization name so that I can share it with you.

https://dev.azure.com/<your-organization-name???>

**Comment by bryanbcook** [comment]
closing this because it [isn't possible to share the extension][1] without the organization name.

[1]: https://github.com/bryanbcook/azdevops-testplan-extension/blob/main/docs/Installation.md
