### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by b-kaf** [bryanbcook/azdevops-testplan-extension#39]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- (required) Organization Name: https://dev.azure.com/aksia

The Technology stack that best describes my scenario:

- [x] JavaScript / TypeScript

Result format that I plan to use:

- [x] JUnit

The Azure Pipeline Agent I intended to use is a:

- [x] Linux - Microsoft cloud hosted

I intend to use the Test Plan extension in:

- [x] YAML Pipeline

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/azuredevops-testplan-extension/blob/main/docs/Installation.md
