### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by dnnaaa** [bryanbcook/azdevops-testplan-extension#4]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/sdxcloud

The Technology stack that best describes my scenario:

- [ ] Java
- [ ] .NET
- [ ] JavaScript / TypeScript
- [x] Other: PowerShell / Pester

Result format that I plan to use:

- [ ] JUnit
- [ ] xUnit
- [ ] MSTest (trx)
- [x] NUnit
- [ ] Other: ____

**Comment by bryanbcook** [comment]
You've been added to the private preview. The extension will appear in "_Organizational Settings > Extensions_" under the _Shared_ tab.
