### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by Knthcame** [bryanbcook/azdevops-testplan-extension#42]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- (required) Organization Name: https://dev.azure.com/YPSOMEDAG

The Technology stack that best describes my scenario:

- [X] Other: Kotlin Multiplatform (Kotlin & Swift)

Result format that I plan to use:

- [X] JUnit

The Azure Pipeline Agent I intended to use is a:

- [X] MacOS - Microsoft cloud hosted

I intend to use the Test Plan extension in:

- [X] YAML Pipeline

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/azdevops-testplan-extension/blob/main/docs/Installation.md
