### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by dbernardo-wtw** [bryanbcook/azdevops-testplan-extension#44]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/wtwdst`):

- (required) Organization Name: https://dev.azure.com/wtwdst

The Technology stack that best describes my scenario:

- [x] .NET

Result format that I plan to use:

- [x] NUnit

The Azure Pipeline Agent I intended to use is a:

- [x] Windows - Self-hosted

I intend to use the Test Plan extension in:

- [x] YAML Pipeline

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/azdevops-testplan-extension/blob/main/docs/Installation.md
