### ISSUE TITLE
Enhancement for lastest Build Number

### ISSUE THREAD

**Issue by sinanmetin** [bryanbcook/azdevops-testplan-extension#45]
Hi Bryan,

thank you for this extension. I have an idea to improvement. When the test results are transferred to Tast Plan, the current Build information does not appear in Test Run. When Test Cases are executed manually, the last Build Number appears, but when we send the results to the Test Plan with the extension, it cannot associate the Build number.
Thanks.

Best Regards,
Sinan Metin

![Screenshot 2024-10-30 163128](https://github.com/user-attachments/assets/794fbd4f-1e13-4da8-9cd8-4bd4c0e3fa7e)

**Comment by bryanbcook** [comment]
This sounds like a great idea.

Just so I understand your screenshot, when you run the tests manually, where is it getting that build number from? Are you providing that value or is it picking it up from somewhere automatically?

Picking up the `$(Build.BuildId)` (and related details) of the pipeline that is publishing the results should be possible. Would that work for you?

**Comment by bryanbcook** [comment]
This has been included in the latest release.

I've included the `$(Build.BuildId)` in the TestRun, which picks up the build-name and link to the pipeline.

![image](https://github.com/user-attachments/assets/04b7a7d5-e166-477e-ab62-64c3eafdfa1e)

I'll leave this open until for a few days or until I hear feedback from you.

I'm using YAML pipelines for the majority of my runs, so I haven't included the Release and Release Stage at this time, though I'm open to including this information if it's useful.

**Comment by michael-genau** [comment]
Hi Bryan,

I just updated the extension on our Azure Dev Ops server.
Thanks a lot!

Just two small issues I fixed locally.

Azure Dev Ops doesn't update the extension if there isn't a new version. 
Azure Dev Ops seems to have a cache and the extension is not updated despite removing and reinstalling it if the version does not change.

The extension uses api versions which are not available for the latest on-premise Azure Dev Ops version.
The latest api version is 7.1 in that case.

**Comment by bryanbcook** [comment]
> Azure Dev Ops doesn't update the extension if there isn't a new version. 
> 
> Azure Dev Ops seems to have a cache and the extension is not updated despite removing and reinstalling it if the version does not change.
> 

Asking for clarification, the extension in the _Organization > Extensions_ should have updated automatically (my organization picked up the new version shortly after the new release was published): are you using a self-hosted build agent on a persistent vm? The build agent detects which tasks are used in the pipeline and downloads them to the agents cache. Most users won't see issues if the build agent is recycled between runs. Sometimes triggering a brand new build or new release fixes the issue. Were you seeing that the task wasn't updated in the Organization or on your build?


> The extension uses api versions which are not available for the latest on-premise Azure Dev Ops version.
> 
> The latest api version is 7.1 in that case.

I'm using a recent version of the node AzureDevOps library. I don't specify api-versions in the request but I can investigate if there is an option to do so. If you are seeing compatibility issues please open a defect.

**Comment by bryanbcook** [comment]
> Normally, we could download the JUnit file containing the test results as an Attachment after the tests were finished in the Pipeline, but we can no longer do this.

I'll have to do some investigation on how attachments are associated to the test run. FYI, I have a separate issue for test case attachments (#21).

> Also the “time” and “timestamp” values are passed to Test Run as 0. Therefore, the Test Duration value is 0 in the Pipeline.

You're right, I use a library to transform different test formats into a common format and I'm not carrying over the original duration into the ADO TestCaseResult. I'll log a separate issue.

**Comment by bryanbcook** [comment]
Closing this defect because the Build Number is showing.
