### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by Jeidoz** [bryanbcook/azdevops-testplan-extension#46]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Havit" (`https://dev.azure.com/havit`):

- (required) Organization Name: https://dev.azure.com/havit

The Technology stack that best describes my scenario:

- [x] .NET

Result format that I plan to use:

- [x] MSTest (trx)

The Azure Pipeline Agent I intended to use is a:

- [x] Windows - Self-hosted

I intend to use the Test Plan extension in:

- [x] Designer-based (Classic) Build Pipeline
- [x] Designer-based (Classic) Release Pipeline

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/azdevops-testplan-extension/blob/main/docs/Installation.md
