### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by quotschmacher** [bryanbcook/azdevops-testplan-extension#5]
I would like to be included in the private preview for this extension!

Please provide your Azure DevOps "Organization Name" (`https://dev.azure.com/<organization-name>`):

- Organization Name: https://dev.azure.com/immo-office

The Technology stack that best describes my scenario:

- [ ] Java
- [ ] .NET
- [ ] JavaScript / TypeScript
- [x] Other: Testcafé

Result format that I plan to use:

- [ ] JUnit
- [x] xUnit
- [ ] MSTest (trx)
- [ ] NUnit
- [ ] Other: ____

**Comment by bryanbcook** [comment]
You've been added to the private preview. The extension will appear in "Organizational Settings > Extensions" under the Shared tab.
